console.log("HITESH CHOUDHary");
//javascript is a dynamically typed language
"use strict"; // treat all JS code as newer version LIKE JISSE OLDER VERSION KA CODE KHARAB NA HO OR COMPLETE HO JAYE
// alert( 3 + 3) // we are using nodejs, not browser SO IT CAUSES AN ERROR 

console.log(3 
    +
     3) // code readability should be high so avoid doing in next lines the same print statements 
//javascript is a dynamically typed language
let name="aditya" //a string datatype
let age=24 //a number datatype
let isloggedin=true//a boolean datatype
let city //this will be an undefined data type which states variable defined but value is not assigned this will be of undefined datatype
let host=null//this is a null data type which by the way is considered as an object but it is intentionally used to display a null value
console.log(host) 
console.log(city)
console.log("type of city ="+typeof(city))//type of to declare typeof variables
/*Undefined → a variable declared but not assigned a value.

let x; // undefined
let id = Symbol("uniqueID"); this is also a dataype used to uniquely identify the elements or components created in further react sessions

Null → represents an intentional empty value.*/
let bigNum = 123456789012345678901234567890n;// big int to represent big nos Creating BigInt

//By adding n at the end of an integer: